### PR TITLE
[v1.24] Add K8s v1.24.13

### PR DESCRIPTION
**Pull request by rayandas**
Related: https://github.com/rancher/rancher/issues/41054 and https://github.com/rancher/rancher/issues/41055

### CODE REVIEW

**Review by kinarashah — CHANGES_REQUESTED** [review]
1. We used `v1.24-custom` branch for v1.24.10 where we needed one tag from `v1.24` downloading kubelet from `kubernetes/kubernetes` and another from `v1.24-custom` downloading kubelet from `rancher/kubernetes`.  We'll be only releasing one version now onwards, so let's forward port the change from https://github.com/rancher/hyperkube/pull/305/files to `v1.24` and use that as the target branch. cc @snasovich lemme know if my assumption is wrong. 

2. The build is failing because you'd first need to create PR under https://github.com/rancher/kubernetes/pull/  to generate a new tag for `v1.24.13`.

**Comment by snasovich** [comment]
> 1. We used `v1.24-custom` branch for v1.24.10 where we needed one tag from `v1.24` downloading kubelet from `kubernetes/kubernetes` and another from `v1.24-custom` downloading kubelet from `rancher/kubernetes`.  We'll be only releasing one version now onwards, so let's forward port the change from [#305 (files)](https://github.com/rancher/hyperkube/pull/305/files) to `v1.24` and use that as the target branch. cc @snasovich lemme know if my assumption is wrong.

@kinarashah , your assumption is totally correct - we're only maintaining versions pulling from `rancher/kubernetes` going forward. That first time we've released both so we have "plan B" in case we find something is terribly wrong with our fork.

**Comment by kinarashah** [comment]
@rayandas I changed the destination branch to v1.24 but when I restart build, it still runs for v1.24-custom. Could you force push and see if that works?

**Comment by rayandas** [comment]
@kinarashah yeah force pushing works.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
