### PR TITLE
Add K8s 1.27.4

### PR DESCRIPTION
**Pull request by rayandas**
Related: https://github.com/rancher/rancher/issues/41840

### CODE REVIEW

**Review by kinarashah — COMMENTED** [review]
could you update to use v1.27.4 to stay in line with client-go version https://github.com/rancher/client-go/releases/tag/v1.27.4-rancher1

**Comment by rayandas** [comment]
@kinarashah Alright! I updated the version. But we need to bump rancher/kubernetes. I will raise a PR for that.

**Comment by kinarashah** [comment]
@rayandas Tagged v1.27.4 in rancher/kubernetes, could you restart drone?

**Comment by rayandas** [comment]
@kinarashah The build was successful.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
