### PR TITLE
[1.22] Add k8s v1.22.7

### PR DESCRIPTION
**Pull request by doflamingo721**
Linked issue:
https://github.com/rancher/rancher/issues/36435

### CODE REVIEW

**Review by kinarashah — COMMENTED** [review]
Needs hyperkube-base update

**Comment by doflamingo721** [comment]
> Needs hyperkube-base update

@kinarashah Should I update the base to `v0.0.10`?

**Comment by kinarashah** [comment]
@doflamingo721 yep, that's the latest I tagged with 1.23. If that fails too, we'll tag a new one.

**Comment by doflamingo721** [comment]
@kinarashah I updated the hyperkube-base in all the PRs and marked them reday for review. Could you please review them again and let me know if it looks good?

**Review by paynejacob — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
