### PR TITLE
Add Zfs

### PR DESCRIPTION
**Pull request by sd-hd**

### CODE REVIEW

**Comment by pdf** [comment]
This PR is filed against master instead of the v1.12 branch, which is why it includes so many commits that already exist on that branch.

**Comment by sd-hd** [comment]
hi peter, i changed the branch from master to v1.12 - sorry

**Comment by smedefind** [comment]
Please merge

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/hyperkube/pull/36

**Pull request closed without merging**
